// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj34t5V7HENP5_Vqx8Ld4dhy0PKmM1TQc',
    appId: '1:369700000583:web:457ab99242cc1e12957262',
    messagingSenderId: '369700000583',
    projectId: 'fir-parking-be8a1',
    authDomain: 'fir-parking-be8a1.firebaseapp.com',
    databaseURL: 'https://fir-parking-be8a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-parking-be8a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoUfaDhWw7xBSvz7a9Yaz4lVzNzkjEJZk',
    appId: '1:369700000583:android:4c9dad0a508b372f957262',
    messagingSenderId: '369700000583',
    projectId: 'fir-parking-be8a1',
    databaseURL: 'https://fir-parking-be8a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-parking-be8a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_WtZSmYBAlfzxEqkftJQU1cNgbWBk9TI',
    appId: '1:369700000583:ios:17e061f414ccf1df957262',
    messagingSenderId: '369700000583',
    projectId: 'fir-parking-be8a1',
    databaseURL: 'https://fir-parking-be8a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-parking-be8a1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_WtZSmYBAlfzxEqkftJQU1cNgbWBk9TI',
    appId: '1:369700000583:ios:17e061f414ccf1df957262',
    messagingSenderId: '369700000583',
    projectId: 'fir-parking-be8a1',
    databaseURL: 'https://fir-parking-be8a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-parking-be8a1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj34t5V7HENP5_Vqx8Ld4dhy0PKmM1TQc',
    appId: '1:369700000583:web:c24a0467b93cd505957262',
    messagingSenderId: '369700000583',
    projectId: 'fir-parking-be8a1',
    authDomain: 'fir-parking-be8a1.firebaseapp.com',
    databaseURL: 'https://fir-parking-be8a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-parking-be8a1.firebasestorage.app',
  );
}